//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace QuestionSystem.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        [Key]
        public int CommentID { get; set; }
        public string Comment { get; set; }
        public int QuestionId { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
